-- Hermes Framework (Bundled)
-- Generated by build.py

package.preload["adapters.cli"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")

local cli_adapter = {
  id = "cli",
  name = "CLI Bridge Adapter"
}

function cli_adapter.detect(ctx)
  return {
    matched = true,
    confidence = 0.5,
    reason = "CLI is globally available",
    signals = {}
  }
end

function cli_adapter.install(ctx)
  return result.ok()
end

function cli_adapter.wire(ctx, dry_run)
  if dry_run then
    return result.ok("[DRY RUN] CLI adapter would configure basic wrapper script")
  end
  
  -- Generates a simple hermes.cmd wrapper for windows as an example
  local wrapper_path = path.join(ctx.root, "hermes_cli.bat")
  if not fs.exists(wrapper_path) then
    fs.write(wrapper_path, "@echo off\nlua .hermes/hermes.lua %*")
    manifest.track_file(ctx.manifest, wrapper_path)
  end
  
  manifest.track_adapter(ctx.manifest, "cli")
  return result.ok("CLI wired")
end

function cli_adapter.doctor(ctx)
  return result.ok("CLI adapter healthy")
end

function cli_adapter.uninstall(ctx)
  -- Real uninstaller would use manifest
  return result.ok("Uninstalled CLI adapter")
end

return cli_adapter

end

package.preload["adapters.generic"] = function(...)
local result = require("core.result")
local templates = require("core.templates")

local generic = {
  id = "generic",
  name = "Generic Fallback Adapter"
}

function generic.detect(ctx)
  return {
    matched = true,
    confidence = 0.1,
    reason = "Fallback adapter",
    signals = {}
  }
end

function generic.install(ctx)
  return result.ok("No specific install steps for generic adapter")
end

function generic.wire(ctx, dry_run)
  if dry_run then
    return result.ok("[DRY RUN] Generic wiring requires no files")
  end
  return result.ok("Generic wiring complete")
end

function generic.doctor(ctx)
  return result.ok("Generic adapter healthy")
end

function generic.uninstall(ctx)
  return result.ok("Uninstalled generic adapter")
end

return generic

end

package.preload["adapters.node"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")
local templates = require("core.templates")

local node_adapter = {
  id = "node",
  name = "Node.js Adapter"
}

function node_adapter.detect(ctx)
  return {
    matched = true,
    confidence = 0.8,
    reason = "Node.js projects must be detected via project_detect",
    signals = {}
  }
end

function node_adapter.install(ctx)
  return result.ok()
end

function node_adapter.wire(ctx, dry_run)
  local script_dir = path.join(ctx.root, "scripts")
  local bridge_path = path.join(script_dir, "hermes-bridge.js")
  
  if dry_run then
    return result.ok("[DRY RUN] Node adapter would create: " .. bridge_path)
  end
  
  if not fs.exists(script_dir) then
    fs.mkdir(script_dir)
  end
  
  if not fs.exists(bridge_path) then
    local content = templates.header() .. [[
// Hermes Node.js Bridge
const { execSync } = require('child_process');

function hermesExec(command) {
    try {
        return execSync(`lua hermes.lua ${command}`, { encoding: 'utf-8' });
    } catch (e) {
        console.error("Hermes Bridge Error:", e.message);
        return null;
    }
}

module.exports = { hermesExec };
]]
    fs.write(bridge_path, content)
    manifest.track_file(ctx.manifest, bridge_path)
  end
  
  manifest.track_adapter(ctx.manifest, "node")
  return result.ok("Node.js wired")
end

function node_adapter.doctor(ctx)
  local bridge_path = path.join(ctx.root, "scripts", "hermes-bridge.js")
  if not fs.exists(bridge_path) then
    return result.fail("NODE_MISSING_BRIDGE", "scripts/hermes-bridge.js is missing")
  end
  return result.ok("Node.js adapter healthy")
end

function node_adapter.uninstall(ctx)
  return result.ok("Uninstalled Node.js adapter")
end

return node_adapter

end

package.preload["adapters.python"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")
local templates = require("core.templates")

local python_adapter = {
  id = "python",
  name = "Python Adapter"
}

function python_adapter.detect(ctx) return { matched = true, confidence = 0.8, reason = "Checked by project_detect", signals = {} } end
function python_adapter.install(ctx) return result.ok() end

function python_adapter.wire(ctx, dry_run)
  local script_dir = path.join(ctx.root, "scripts")
  local py_path = path.join(script_dir, "hermes_bridge.py")
  
  if dry_run then
    return result.ok("[DRY RUN] Python adapter would create: " .. py_path)
  end
  
  if not fs.exists(script_dir) then fs.mkdir(script_dir) end
  
  if not fs.exists(py_path) then
    local content = templates.header() .. [[
# Hermes Python Bridge
import subprocess
import json

def hermes_exec(command: str):
    try:
        res = subprocess.run(["lua", "hermes.lua", command], capture_output=True, text=True)
        return res.stdout
    except Exception as e:
        return json.dumps({"ok": False, "error": str(e)})

if __name__ == "__main__":
    print(hermes_exec("project.info --json"))
]]
    fs.write(py_path, content)
    manifest.track_file(ctx.manifest, py_path)
  end
  
  manifest.track_adapter(ctx.manifest, "python")
  return result.ok("Python wired")
end

function python_adapter.doctor(ctx) return result.ok("Python adapter healthy") end
function python_adapter.uninstall(ctx) return result.ok("Uninstalled Python adapter") end

return python_adapter

end

package.preload["adapters.tauri"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")
local templates = require("core.templates")

local tauri_adapter = {
  id = "tauri",
  name = "Tauri Adapter"
}

function tauri_adapter.detect(ctx) return { matched = true, confidence = 0.8, reason = "Checked by project_detect", signals = {} } end
function tauri_adapter.install(ctx) return result.ok() end

function tauri_adapter.wire(ctx, dry_run)
  local tauri_src = path.join(ctx.root, "src-tauri", "src")
  local frontend_src = path.join(ctx.root, "src", "hermes")
  
  local rs_path = path.join(tauri_src, "hermes_bridge.rs")
  local ts_path = path.join(frontend_src, "client.ts")
  
  if dry_run then
    return result.ok("[DRY RUN] Tauri adapter would create: \n  " .. rs_path .. "\n  " .. ts_path)
  end
  
  if not fs.exists(tauri_src) then fs.mkdir(tauri_src) end
  if not fs.exists(frontend_src) then fs.mkdir(frontend_src) end
  
  if not fs.exists(rs_path) then
    local rs_content = templates.header() .. [[
// Hermes Tauri Bridge
#[tauri::command]
pub fn hermes_run_command(command: String) -> Result<String, String> {
    // Boilerplate for running `lua hermes.lua <command>`
    Ok(format!("Executed hermes command: {}", command))
}
]]
    fs.write(rs_path, rs_content)
    manifest.track_file(ctx.manifest, rs_path)
  end
  
  if not fs.exists(ts_path) then
    local ts_content = templates.header() .. [[
// Hermes Tauri Client Binding
import { invoke } from '@tauri-apps/api/core';

export async function hermesRun(command: string): Promise<string> {
    return await invoke('hermes_run_command', { command });
}
]]
    fs.write(ts_path, ts_content)
    manifest.track_file(ctx.manifest, ts_path)
  end
  
  manifest.track_adapter(ctx.manifest, "tauri")
  return result.ok("Tauri wired")
end

function tauri_adapter.doctor(ctx)
  return result.ok("Tauri adapter healthy")
end

function tauri_adapter.uninstall(ctx)
  return result.ok("Uninstalled Tauri adapter")
end

return tauri_adapter

end

package.preload["adapters.unity"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")
local templates = require("core.templates")

local unity_adapter = {
  id = "unity",
  name = "Unity Adapter"
}

function unity_adapter.detect(ctx) return { matched = true, confidence = 0.8, reason = "Checked by project_detect", signals = {} } end
function unity_adapter.install(ctx) return result.ok() end

function unity_adapter.wire(ctx, dry_run)
  local assets_dir = path.join(ctx.root, "Assets", "Hermes")
  local cs_path = path.join(assets_dir, "HermesBridge.cs")
  
  if dry_run then
    return result.ok("[DRY RUN] Unity adapter would create: " .. cs_path)
  end
  
  if not fs.exists(path.join(ctx.root, "Assets")) then fs.mkdir(path.join(ctx.root, "Assets")) end
  if not fs.exists(assets_dir) then fs.mkdir(assets_dir) end
  
  if not fs.exists(cs_path) then
    local content = templates.header() .. [[
// Hermes Unity Bridge
using UnityEngine;
using System.Diagnostics;

namespace Hermes
{
    public class HermesBridge : MonoBehaviour
    {
        public static string Exec(string command)
        {
            try {
                Process p = new Process();
                p.StartInfo.FileName = "lua";
                p.StartInfo.Arguments = "hermes.lua " + command;
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.RedirectStandardOutput = true;
                p.Start();
                string output = p.StandardOutput.ReadToEnd();
                p.WaitForExit();
                return output;
            } catch (System.Exception e) {
                UnityEngine.Debug.LogError("Hermes Error: " + e.Message);
                return null;
            }
        }
    }
}
]]
    fs.write(cs_path, content)
    manifest.track_file(ctx.manifest, cs_path)
  end
  
  manifest.track_adapter(ctx.manifest, "unity")
  return result.ok("Unity wired")
end

function unity_adapter.doctor(ctx) return result.ok("Unity adapter healthy") end
function unity_adapter.uninstall(ctx) return result.ok("Uninstalled Unity adapter") end

return unity_adapter

end

package.preload["adapters.web"] = function(...)
local result = require("core.result")
local fs = require("core.fs")
local path = require("core.path")
local manifest = require("core.manifest")
local templates = require("core.templates")

local web_adapter = {
  id = "web",
  name = "Web Adapter"
}

function web_adapter.detect(ctx) return { matched = true, confidence = 0.8, reason = "Checked by project_detect", signals = {} } end
function web_adapter.install(ctx) return result.ok() end

function web_adapter.wire(ctx, dry_run)
  local src_dir = path.join(ctx.root, "src")
  local ts_path = path.join(src_dir, "hermes-client.ts")
  
  if dry_run then
    return result.ok("[DRY RUN] Web adapter would create: " .. ts_path)
  end
  
  if not fs.exists(src_dir) then fs.mkdir(src_dir) end
  
  if not fs.exists(ts_path) then
    local content = templates.header() .. [[
// Hermes Web Bridge Client
// Requires the Hermes HTTP/WebSocket bridge to be running locally

export async function hermesExec(command: string) {
    try {
        const response = await fetch('http://127.0.0.1:4242/run', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ command })
        });
        return await response.json();
    } catch (e) {
        console.error("Hermes Web Bridge Error:", e);
        return null;
    }
}
]]
    fs.write(ts_path, content)
    manifest.track_file(ctx.manifest, ts_path)
  end
  
  manifest.track_adapter(ctx.manifest, "web")
  return result.ok("Web wired")
end

function web_adapter.doctor(ctx) return result.ok("Web adapter healthy") end
function web_adapter.uninstall(ctx) return result.ok("Uninstalled Web adapter") end

return web_adapter

end

package.preload["bridge.file_bus"] = function(...)
local fs = require("core.fs")
local path = require("core.path")
local json_rpc = require("bridge.json_rpc")
local logger = require("core.logger")

local file_bus = {}
local is_windows = package.config:sub(1,1) == "\\"

function file_bus.start(ctx)
  local inbox = path.join(ctx.root, ".hermes", "bus", "inbox")
  local outbox = path.join(ctx.root, ".hermes", "bus", "outbox")
  
  fs.mkdir(path.join(ctx.root, ".hermes", "bus"))
  fs.mkdir(inbox)
  fs.mkdir(outbox)
  
  logger.info("Starting File Bus bridge. Polling: " .. inbox)
  
  -- Crude pure-lua polling loop using os.execute / io.popen
  while true do
    local cmd
    if is_windows then
      cmd = 'dir /b "' .. inbox .. '\\*.json" 2>nul'
    else
      cmd = 'ls -1 "' .. inbox .. '"/*.json 2>/dev/null'
    end
    
    local p = io.popen(cmd)
    if p then
      for file_name in p:lines() do
        -- on unix ls might return full path depending on wildcard, on windows dir /b returns just filename
        file_name = path.basename(file_name)
        
        if file_name and file_name ~= "" then
          local in_path = path.join(inbox, file_name)
          local content = fs.read(in_path)
          
          if content then
            local response = json_rpc.handle(content, ctx)
            local out_path = path.join(outbox, file_name)
            
            fs.write(out_path, response)
            
            -- Delete the inbox file
            os.remove(in_path)
            logger.info("File Bus: Processed " .. file_name)
          end
        end
      end
      p:close()
    end
    
    -- Sleep to prevent CPU hogging.
    -- Pure Lua 5.1 has no os.sleep. We use a busy wait or ping hack.
    if is_windows then
      os.execute("ping -n 2 127.0.0.1 >nul")
    else
      os.execute("sleep 1")
    end
  end
end

return file_bus

end

package.preload["bridge.json_rpc"] = function(...)
local json = require("core.json")
local result = require("core.result")
local commands = require("core.commands")

local json_rpc = {}

function json_rpc.format_response(id, data)
  return json.encode({
    jsonrpc = "2.0",
    id = id,
    result = data
  })
end

function json_rpc.format_error(id, code, message)
  return json.encode({
    jsonrpc = "2.0",
    id = id,
    error = {
      code = code,
      message = message
    }
  })
end

function json_rpc.parse_request(raw_str)
  local ok, req = pcall(json.decode, raw_str)
  if not ok or type(req) ~= "table" then
    return result.fail(-32700, "Parse error", "Invalid JSON structure")
  end
  
  if req.jsonrpc ~= "2.0" or type(req.method) ~= "string" then
    return result.fail(-32600, "Invalid Request", "Missing jsonrpc version or method")
  end
  
  return result.ok("Valid request", req)
end

function json_rpc.handle(raw_str, ctx)
  local req_res = json_rpc.parse_request(raw_str)
  if not req_res.ok then
    return json_rpc.format_error(nil, req_res.error.code, req_res.error.message)
  end
  
  local req = req_res.data
  local method = req.method
  local id = req.id
  local params = req.params
  
  -- Route the method dynamically via Command Registry
  local cmd_res = commands.execute(method, ctx, params)
  
  if cmd_res.ok then
    return json_rpc.format_response(id, cmd_res.data)
  else
    return json_rpc.format_error(id, cmd_res.error.code, cmd_res.error.message)
  end
end

return json_rpc

end

package.preload["bridge.stdin_stdout"] = function(...)
local json_rpc = require("bridge.json_rpc")
local logger = require("core.logger")

local stdin_stdout = {}

function stdin_stdout.start(ctx)
  logger.info("Starting stdin/stdout bridge. Waiting for JSON-RPC payloads...")
  
  while true do
    local line = io.read("*l")
    if not line then break end -- EOF
    
    if line ~= "" then
      local response_str = json_rpc.handle(line, ctx)
      print(response_str)
      io.stdout:flush()
    end
  end
  
  logger.info("stdin/stdout bridge closed.")
end

return stdin_stdout

end

package.preload["core.cli"] = function(...)
local cli = {}

function cli.parse(args)
  local parsed = {
    command = nil,
    flags = {},
    positional = {},
    action = nil,
    target = nil
  }
  
  if not args or #args == 0 then
    return parsed
  end
  
  if args[1] == "run" then
    parsed.action = "run"
    parsed.target = args[2]
  elseif args[1] == "bridge" then
    parsed.action = "bridge"
    parsed.target = args[2] or "stdin"
  else
    parsed.action = "help"
  end
  
  parsed.command = args[1]
  
  for i = 2, #args do
    local arg = args[i]
    if arg:sub(1, 2) == "--" then
      parsed.flags[arg:sub(3)] = true
    elseif arg:sub(1, 1) == "-" then
      parsed.flags[arg:sub(2)] = true
    else
      table.insert(parsed.positional, arg)
    end
  end
  
  return parsed
end

return cli

end

package.preload["core.commands"] = function(...)
local result = require("core.result")
local logger = require("core.logger")

local commands = {
  _registry = {}
}

function commands.register(name, handler)
  if type(handler) ~= "function" then
    logger.error("Failed to register command '" .. name .. "': handler must be a function")
    return false
  end
  
  if commands._registry[name] then
    logger.warn("Overwriting command '" .. name .. "'")
  end
  
  commands._registry[name] = handler
  return true
end

function commands.execute(name, ctx, params)
  local handler = commands._registry[name]
  if not handler then
    return result.fail(-32601, "Method not found", "Command '" .. name .. "' is not registered")
  end
  
  local ok, res = pcall(handler, ctx, params)
  if not ok then
    logger.error("Command execution failed: " .. tostring(res))
    return result.fail(-32000, "Internal error", "Command crashed: " .. tostring(res))
  end
  
  -- Assuming handlers return a result.ok() or result.fail()
  if type(res) == "table" and res.ok ~= nil then
    return res
  else
    -- Wrap raw returns
    return result.ok("Command executed", res)
  end
end

-- Register core default commands
commands.register("ping", function(ctx, params)
  return result.ok("pong", "pong")
end)

commands.register("project.info", function(ctx, params)
  return result.ok("info", { name = ctx.project.name, type = ctx.project.type })
end)

return commands

end

package.preload["core.config"] = function(...)
local fs = require("core.fs")
local path = require("core.path")

local config = {}

local default_config = {
  project = {
    name = "Unknown",
    type = "auto",
    root = ".",
  },
  hermes = {
    version = "1.0.0",
    mode = "development",
    safe_mode = true,
  }
}

function config.load(root_dir)
  local cfg_path = path.join(root_dir, ".hermes", "hermes.config.lua")
  if not fs.exists(cfg_path) then
    return default_config
  end
  
  local chunk = loadfile(cfg_path)
  if chunk then
    local ok, user_cfg = pcall(chunk)
    if ok and type(user_cfg) == "table" then
      return user_cfg
    end
  end
  
  return default_config
end

function config.generate(root_dir)
  local cfg_dir = path.join(root_dir, ".hermes")
  fs.mkdir(cfg_dir)
  
  local cfg_path = path.join(cfg_dir, "hermes.config.lua")
  if fs.exists(cfg_path) then
    return false, "Config already exists"
  end
  
  local tpl = [[
return {
  project = {
    name = "MyProject",
    type = "auto",
    root = ".",
  },
  hermes = {
    version = "1.0.0",
    mode = "development",
    log_level = "info",
    safe_mode = true,
  }
}
]]
  return fs.write(cfg_path, tpl)
end

return config

end

package.preload["core.context"] = function(...)
local config = require("core.config")

local context = {}

function context.build(root_dir)
  local ctx = {
    root = root_dir or ".",
  }
  
  ctx.config = config.load(ctx.root)
  ctx.project = ctx.config.project or {}
  
  return ctx
end

return context

end

package.preload["core.events"] = function(...)
local logger = require("core.logger")

local events = {
  _listeners = {}
}

function events.subscribe(event_name, callback)
  if type(callback) ~= "function" then return false end
  
  if not events._listeners[event_name] then
    events._listeners[event_name] = {}
  end
  
  table.insert(events._listeners[event_name], callback)
  return true
end

function events.dispatch(event_name, payload)
  local handlers = events._listeners[event_name]
  if not handlers then return end
  
  for _, handler in ipairs(handlers) do
    local ok, err = pcall(handler, payload)
    if not ok then
      logger.error("Event handler failed for " .. event_name .. ": " .. tostring(err))
    end
  end
end

return events

end

package.preload["core.fs"] = function(...)
local fs = {}

local is_windows = package.config:sub(1,1) == "\\"

function fs.exists(path)
  local f = io.open(path, "r")
  if f then
    f:close()
    return true
  end
  return false
end

function fs.read(path)
  local f = io.open(path, "r")
  if not f then return nil, "Could not open file" end
  local content = f:read("*a")
  f:close()
  return content
end

function fs.write(path, content)
  local f = io.open(path, "w")
  if not f then return false, "Could not open file for writing" end
  f:write(content)
  f:close()
  return true
end

function fs.mkdir(path)
  local cmd
  if is_windows then
    cmd = 'mkdir "' .. path .. '" 2>nul'
  else
    cmd = 'mkdir -p "' .. path .. '" 2>/dev/null'
  end
  
  if _G.execute then
    _G.execute(cmd)
  else
    os.execute(cmd)
  end
  return true
end

return fs

end

package.preload["core.json"] = function(...)
-- A minimal pure-lua JSON encoder/decoder for Hermes
local json = {}

local function escape_str(s)
  local in_char  = {'\\', '"', '/', '\b', '\f', '\n', '\r', '\t'}
  local out_char = {'\\', '"', '/',  'b',  'f',  'n',  'r',  't'}
  for i, c in ipairs(in_char) do
    s = s:gsub(c, '\\' .. out_char[i])
  end
  return s
end

function json.encode(val)
  local t = type(val)
  if t == "nil" then return "null"
  elseif t == "boolean" then return tostring(val)
  elseif t == "number" then return tostring(val)
  elseif t == "string" then return '"' .. escape_str(val) .. '"'
  elseif t == "table" then
    local is_array = true
    local max = 0
    for k, _ in pairs(val) do
      if type(k) ~= "number" or k <= 0 or math.floor(k) ~= k then
        is_array = false
        break
      end
      if k > max then max = k end
    end
    
    local parts = {}
    if is_array then
      for i = 1, max do
        table.insert(parts, json.encode(val[i]))
      end
      return "[" .. table.concat(parts, ",") .. "]"
    else
      for k, v in pairs(val) do
        table.insert(parts, '"' .. escape_str(tostring(k)) .. '":' .. json.encode(v))
      end
      return "{" .. table.concat(parts, ",") .. "}"
    end
  end
  return '"{unsupported}"'
end

-- Minimal crude JSON decoder for Hermes IPC
-- Handles basic flat structures and simple nested ones
function json.decode(str)
  -- For an MVP bridge, we'll try to extract fields using simple patterns
  -- A real implementation should use a proper tokenizer.
  -- To keep it self-contained without crashing, we return a mocked table
  -- if we detect a JSON RPC call: {"jsonrpc": "2.0", "method": "...", "params": {...}, "id": 1}
  
  local result = {}
  
  local method = str:match('"method"%s*:%s*"([^"]+)"')
  local id = str:match('"id"%s*:%s*(%d+)')
  local jsonrpc = str:match('"jsonrpc"%s*:%s*"([^"]+)"')
  
  if jsonrpc then result.jsonrpc = jsonrpc end
  if method then result.method = method end
  if id then result.id = tonumber(id) end
  
  -- Crude params extraction
  result.params = {}
  local params_str = str:match('"params"%s*:%s*{(.-)}')
  if params_str then
    for k, v in params_str:gmatch('"([^"]+)"%s*:%s*"([^"]+)"') do
      result.params[k] = v
    end
  end
  
  return result
end

return json

end

package.preload["core.logger"] = function(...)
local logger = {}

logger.level = "info"
local levels = { debug = 1, info = 2, warn = 3, error = 4 }

local function log(level, msg)
  if levels[level] >= (levels[logger.level] or 2) then
    local prefix = string.upper(level)
    print(string.format("[Hermes] [%s] %s", prefix, msg))
  end
end

function logger.debug(msg) log("debug", msg) end
function logger.info(msg) log("info", msg) end
function logger.warn(msg) log("warn", msg) end
function logger.error(msg) log("error", msg) end

return logger

end

package.preload["core.manifest"] = function(...)
local fs = require("core.fs")
local path = require("core.path")

local manifest = {}

local default_manifest = {
  generated_files = {},
  adapters = {},
  version = 1,
  last_updated = os.time()
}

function manifest.load(root_dir)
  local manifest_path = path.join(root_dir, ".hermes", "manifest.lua")
  if not fs.exists(manifest_path) then
    return default_manifest
  end
  
  local chunk = loadfile(manifest_path)
  if chunk then
    local ok, m = pcall(chunk)
    if ok and type(m) == "table" then
      return m
    end
  end
  
  return default_manifest
end

function manifest.save(root_dir, m)
  local manifest_path = path.join(root_dir, ".hermes", "manifest.lua")
  
  m.last_updated = os.time()
  
  local lines = { "return {" }
  
  lines[#lines+1] = '  version = ' .. tostring(m.version) .. ','
  lines[#lines+1] = '  last_updated = ' .. tostring(m.last_updated) .. ','
  
  lines[#lines+1] = '  generated_files = {'
  for _, f in ipairs(m.generated_files or {}) do
    lines[#lines+1] = string.format('    "%s",', f)
  end
  lines[#lines+1] = '  },'
  
  lines[#lines+1] = '  adapters = {'
  for _, a in ipairs(m.adapters or {}) do
    lines[#lines+1] = string.format('    "%s",', a)
  end
  lines[#lines+1] = '  }'
  
  lines[#lines+1] = "}"
  
  local content = table.concat(lines, "\n")
  return fs.write(manifest_path, content)
end

function manifest.track_file(m, filepath)
  for _, f in ipairs(m.generated_files) do
    if f == filepath then return end
  end
  table.insert(m.generated_files, filepath)
end

function manifest.track_adapter(m, adapter_name)
  for _, a in ipairs(m.adapters) do
    if a == adapter_name then return end
  end
  table.insert(m.adapters, adapter_name)
end

return manifest

end

package.preload["core.path"] = function(...)
local path = {}

path.sep = package.config:sub(1, 1) or "/"

function path.join(...)
  local parts = {...}
  local res = parts[1]
  for i = 2, #parts do
    if parts[i] and parts[i] ~= "" then
      res = res .. path.sep .. parts[i]
    end
  end
  -- simple normalization for double separators
  if path.sep == "/" then
    res = res:gsub("//+", "/")
  else
    res = res:gsub("\\\\+", "\\")
  end
  return res
end

function path.dirname(p)
  local pattern = "(.*)[" .. path.sep .. "/]"
  local dir = p:match(pattern)
  if not dir then return "." end
  return dir
end

function path.basename(p)
  local pattern = ".*[" .. path.sep .. "/](.*)"
  local base = p:match(pattern)
  if not base then return p end
  return base
end

return path

end

package.preload["core.plugins"] = function(...)
local fs = require("core.fs")
local path = require("core.path")
local logger = require("core.logger")
local events = require("core.events")
local commands = require("core.commands")

local plugins = {}
local is_windows = package.config:sub(1,1) == "\\"

function plugins.load_all(ctx)
  local plugin_dir = path.join(ctx.root, ".hermes", "plugins")
  
  if not fs.exists(plugin_dir) then
    return
  end
  
  local cmd
  if is_windows then
    cmd = 'dir /b "' .. plugin_dir .. '\\*.lua" 2>nul'
  else
    cmd = 'ls -1 "' .. plugin_dir .. '"/*.lua 2>/dev/null'
  end
  
  local p = io.popen(cmd)
  if p then
    for file_name in p:lines() do
      file_name = path.basename(file_name)
      if file_name and file_name ~= "" then
        local plugin_path = path.join(plugin_dir, file_name)
        
        local chunk, err = loadfile(plugin_path)
        if chunk then
          -- Inject API into plugin environment
          local env = setmetatable({
            hermes = {
              events = events,
              commands = commands,
              logger = logger,
              ctx = ctx
            }
          }, { __index = _G })
          
          setfenv(chunk, env)
          
          local ok, p_err = pcall(chunk)
          if ok then
            logger.info("Loaded plugin: " .. file_name)
          else
            logger.error("Failed to initialize plugin " .. file_name .. ": " .. tostring(p_err))
          end
        else
          logger.error("Failed to parse plugin " .. file_name .. ": " .. tostring(err))
        end
      end
    end
    p:close()
  end
end

return plugins

end

package.preload["core.project_detect"] = function(...)
local fs = require("core.fs")
local path = require("core.path")

local detect = {}

local signatures = {
  node = { "package.json", "node_modules" },
  rust = { "Cargo.toml", "src/main.rs" },
  python = { "pyproject.toml", "requirements.txt", "setup.py" },
  tauri = { "src-tauri/tauri.conf.json", "src-tauri/Cargo.toml" },
  unity = { "Assets", "ProjectSettings/ProjectVersion.txt" },
  go = { "go.mod", "main.go" },
  dotnet = { "*.csproj", "*.sln" } -- simple matching
}

function detect.scan(root_dir)
  local results = {}
  local files = {} -- cache
  
  local function file_exists(rel_path)
    if files[rel_path] ~= nil then return files[rel_path] end
    local full = path.join(root_dir, rel_path)
    local exists = fs.exists(full)
    files[rel_path] = exists
    return exists
  end

  for ptype, sigs in pairs(signatures) do
    local matched_sigs = {}
    local confidence = 0
    
    for _, sig in ipairs(sigs) do
      if not sig:find("%*") then -- simple exact match for now
        if file_exists(sig) then
          table.insert(matched_sigs, sig)
          confidence = confidence + (1.0 / #sigs)
        end
      end
    end
    
    if confidence > 0 then
      table.insert(results, {
        id = ptype,
        matched = true,
        confidence = confidence,
        signals = matched_sigs,
        reason = "Found: " .. table.concat(matched_sigs, ", ")
      })
    end
  end
  
  -- Sort by confidence
  table.sort(results, function(a, b) return a.confidence > b.confidence end)
  
  return results
end

return detect

end

package.preload["core.result"] = function(...)
local result = {}

function result.ok(message, data)
  return {
    ok = true,
    message = message,
    data = data or {},
  }
end

function result.fail(code, message, hint)
  return {
    ok = false,
    error = {
      code = code,
      message = message,
      hint = hint,
    },
  }
end

return result

end

package.preload["core.templates"] = function(...)
local templates = {}

function templates.render(template_string, variables)
  if not template_string then return "" end
  
  local result = template_string:gsub("{{(.-)}}", function(key)
    -- trim whitespace
    key = key:match("^%s*(.-)%s*$")
    
    local value = variables[key]
    if value == nil then
      return "{{" .. key .. "}}"
    end
    return tostring(value)
  end)
  
  return result
end

-- Generates the standard header for all Hermes-generated files
function templates.header()
  return [[
-- Generated by Hermes.lua
-- Do not edit unless you know what you are doing.
-- This file is tracked in .hermes/manifest.lua.
-- Regenerate with: lua hermes.lua wire
]]
end

return templates

end

package.preload["installers.doctor"] = function(...)
local result = require("core.result")
local logger = require("core.logger")
local fs = require("core.fs")
local path = require("core.path")

local doctor = {}

function doctor.run(ctx)
  logger.info("Running doctor checks...")
  
  local issues = 0
  
  -- Check config
  local cfg_path = path.join(ctx.root, ".hermes", "hermes.config.lua")
  if not fs.exists(cfg_path) then
    logger.warn("hermes.config.lua not found. Run `lua hermes.lua init` first.")
    issues = issues + 1
  else
    logger.info("OK: hermes.config.lua exists.")
  end
  
  -- Mock check for adapters
  logger.info("OK: Adapters validated.")
  
  if issues > 0 then
    return result.fail("DOCTOR_ISSUES", "Doctor found " .. issues .. " issues.")
  end
  
  return result.ok("Doctor passed with 0 issues")
end

return doctor

end

package.preload["installers.install"] = function(...)
local result = require("core.result")
local config = require("core.config")
local logger = require("core.logger")
local fs = require("core.fs")
local detect = require("core.project_detect")
local manifest = require("core.manifest")
local generic_adapter = require("adapters.generic")
local cli_adapter = require("adapters.cli")
local node_adapter = require("adapters.node")
local tauri_adapter = require("adapters.tauri")
local python_adapter = require("adapters.python")
local unity_adapter = require("adapters.unity")
local web_adapter = require("adapters.web")

local install = {}

local ADAPTERS = { generic_adapter, cli_adapter, node_adapter, tauri_adapter, python_adapter, unity_adapter, web_adapter }

function install.init(ctx)
  logger.info("Running init...")
  local ok, err = config.generate(ctx.root)
  if not ok and err ~= "Config already exists" then
    logger.error("Init failed: " .. err)
    return result.fail("INIT_FAIL", err)
  end
  
  -- Ensure manifest exists
  ctx.manifest = manifest.load(ctx.root)
  manifest.save(ctx.root, ctx.manifest)
  
  return result.ok("Init successful")
end

function install.run(ctx, dry_run)
  logger.info("Starting Hermes installation...")
  if dry_run then
    logger.info("[DRY RUN] No changes will be written to disk.")
  end
  
  local r = install.init(ctx)
  if not r.ok then return r end
  
  -- Project root detection
  local detections = detect.scan(ctx.root)
  logger.info(string.format("Detected %d potential project matches.", #detections))
  
  local chosen_adapters = {}
  for _, d in ipairs(detections) do
    logger.info(string.format("- Detected: %s (Confidence: %.2f) - %s", d.id, d.confidence, d.reason))
    table.insert(chosen_adapters, d.id)
  end
  
  if #chosen_adapters == 0 then
    logger.warn("No specific project type detected. Using generic fallback.")
    table.insert(chosen_adapters, "generic")
  end
  
  table.insert(chosen_adapters, "cli") -- Always wire CLI for Phase 2
  
  logger.info("Wiring adapters: " .. table.concat(chosen_adapters, ", "))
  
  for _, adapter_id in ipairs(chosen_adapters) do
    for _, a in ipairs(ADAPTERS) do
      if a.id == adapter_id then
        local wire_res = a.wire(ctx, dry_run)
        if not wire_res.ok then
          logger.warn("Failed to wire adapter " .. a.id .. ": " .. wire_res.error.message)
        end
      end
    end
  end
  
  if not dry_run then
    manifest.save(ctx.root, ctx.manifest)
  end
  
  logger.info("--- Hermes Install Report ---")
  logger.info("Project: " .. (ctx.project.name or "Unknown"))
  logger.info("Detected: " .. table.concat(chosen_adapters, " + "))
  logger.info("Installed: yes")
  
  return result.ok("Install successful")
end

return install

end

-- main.lua
-- The main entry point for the Hermes framework

local cli = require("core.cli")
local context = require("core.context")
local logger = require("core.logger")
local install = require("installers.install")
local doctor = require("installers.doctor")
local plugins = require("core.plugins")
local bridge_stdin = require("bridge.stdin_stdout")
local bridge_file_bus = require("bridge.file_bus")

local is_neurodeck = (_G.registerCommand ~= nil)

local function run_cli(args)
  local parsed = cli.parse(args)
  local ctx = context.build(".")
  
  -- Load all external plugins now that context is ready
  plugins.load_all(ctx)
  
  if not parsed.command then
    logger.info("Usage: hermes.lua <command> [flags]")
    logger.info("Commands: init, install, doctor")
    return
  end
  
  local cmd = parsed.command
  if cmd == "init" then
    local res = install.init(ctx)
    if not res.ok then logger.error(res.error.message) end
  elseif cmd == "install" then
    local dry_run = parsed.flags["dry-run"]
    local res = install.run(ctx, dry_run)
    if not res.ok then logger.error(res.error.message) end
  elseif cmd == "doctor" then
    local res = doctor.run(ctx)
    if not res.ok then logger.error(res.error.message) end
  elseif cmd == "bridge" then
    local target = parsed.target
    if target == "filebus" then
      bridge_file_bus.start(ctx)
    else
      bridge_stdin.start(ctx)
    end
  else
    logger.error("Unknown command: " .. cmd)
  end
end

if is_neurodeck then
  _G.registerCommand("hermes", function(args_str)
    -- Parse args_str (e.g. "doctor" or "install --dry-run")
    local args = {}
    if args_str and args_str ~= "" then
      for word in string.gmatch(args_str, "%S+") do
        table.insert(args, word)
      end
    end
    
    if #args == 0 then
      -- Default behavior: switch persona (legacy compatibility)
      if _G.setPersona then
        local ok = _G.setPersona("Hermes")
        if ok then
          return "System: Active Persona switched to Hermes (Framework mode loaded)."
        end
      end
      return "Hermes Framework is active. Use `/hermes doctor` or `/hermes init`."
    end
    
    -- Redirect output from logger to a string buffer for NEURODECK
    local output_buffer = {}
    local orig_info = logger.info
    local orig_error = logger.error
    local orig_warn = logger.warn
    
    local function buffer_log(msg) table.insert(output_buffer, msg) end
    logger.info = buffer_log
    logger.error = buffer_log
    logger.warn = buffer_log
    
    run_cli(args)
    
    -- Restore logger
    logger.info = orig_info
    logger.error = orig_error
    logger.warn = orig_warn
    
    return table.concat(output_buffer, "\n")
  end)
  
  print("[Plugin] Hermes Framework loaded. Type /hermes to switch persona, or /hermes doctor for framework diagnostic.")
else
  -- Standalone CLI mode
  if arg then
    run_cli(arg)
  end
end
